# Site settings
title: Angel Casado
email: hello@angelcasado.net
description: "Product guy"
baseurl: ""
url: "http://angelcasado.net"

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Social
github: angelcasado
twitter: angelcasado
instagram: _angelcasado
